baseURL = ""
languageCode = "en-us"
title = "Venture Educational Collaborative"
[params]
tagline = "Think Big, Think Innovatively!"
about = "Venture Educational Collaborative is an interdisciplinary team of school leaders and teachers."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true